[package]
name = "tack-assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
tack-storage.workspace = true
tack-core.workspace = true
image.workspace = true
png.workspace = true
jpeg-decoder.workspace = true
turbojpeg.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
crc32fast.workspace = true
sha2.workspace = true

[dev-dependencies]
image = { workspace = true, features = ["jpeg"] }

[lints]
workspace = true
