//! Opt-in serial provider comparison; never part of the ordinary test gate.
use super::*;
use std::{collections::BTreeMap, fs::File};

type Pixels = BTreeMap<u32, image::RgbaImage>;

struct CountRead {
    source: File,
    bytes: u64,
}
impl Read for CountRead {
    fn read(&mut self, target: &mut [u8]) -> std::io::Result<usize> {
        let read = self.source.read(target)?;
        self.bytes += read as u64;
        Ok(read)
    }
}

fn rectangle(width: u32) -> Result<Vec<u32>, AssetError> {
    (190..193)
        .flat_map(|y| (190..190 + width).map(move |x| Tile { mip: 0, x, y }.tag()))
        .collect()
}

#[derive(Default)]
struct Measurement {
    pixels: Pixels,
    source_reads: u64,
    crop_peak: u64,
    output_peak: usize,
}

fn measure(
    path: &std::path::Path,
    jobs: &[Vec<u32>],
    single: bool,
) -> Result<Measurement, AssetError> {
    let mut measured = Measurement::default();
    for edges in jobs {
        let mut source = CountRead {
            source: File::open(path)?,
            bytes: 0,
        };
        let header = jpeg_header::read(&mut source)?;
        if header.size != [50_000; 2] {
            return Err("regional comparison requires the exact 50000-square fixture".into());
        }
        let crop = batch_plan(header.size, edges)?.region.native;
        measured.crop_peak = measured
            .crop_peak
            .max(u64::from(crop[0]) * u64::from(crop[1]) * 4);
        let outputs = if single {
            vec![derive(&mut source, header, edges[0], None)?]
        } else {
            derive_tiles(&mut source, header, edges, None)?
        };
        measured.source_reads += source.bytes;
        measured.output_peak = measured
            .output_peak
            .max(outputs.iter().map(|p| p.as_raw().len()).sum());
        for (&edge, pixels) in edges.iter().zip(outputs) {
            measured.pixels.insert(edge, pixels);
        }
    }
    Ok(measured)
}

// A sampled /proc process HWM is distinct from decoder allocation accounting.
#[cfg(target_os = "linux")]
fn child_rss() -> u64 {
    let tasks = format!("/proc/{}/task", std::process::id());
    let Ok(tasks) = std::fs::read_dir(tasks) else {
        return 0;
    };
    let mut peak = 0;
    for task in tasks.flatten() {
        let Ok(children) = std::fs::read_to_string(task.path().join("children")) else {
            continue;
        };
        for child in children.split_whitespace() {
            let Ok(status) = std::fs::read_to_string(format!("/proc/{child}/status")) else {
                continue;
            };
            for line in status
                .lines()
                .filter(|line| line.starts_with("VmHWM:") || line.starts_with("VmRSS:"))
            {
                if let Some(kib) = line
                    .split_whitespace()
                    .nth(1)
                    .and_then(|value| value.parse::<u64>().ok())
                {
                    peak = peak.max(kib * 1024);
                }
            }
        }
    }
    peak
}
#[cfg(not(target_os = "linux"))]
fn child_rss() -> u64 {
    0
}

fn sampled(
    work: impl FnOnce() -> Result<Measurement, AssetError>,
) -> Result<(Measurement, u64), AssetError> {
    let finished = AtomicBool::new(false);
    std::thread::scope(|scope| {
        let observer = scope.spawn(|| {
            let mut peak = 0;
            while !finished.load(Ordering::Acquire) {
                peak = peak.max(child_rss());
                std::thread::sleep(Duration::from_millis(5));
            }
            peak
        });
        let result = work();
        finished.store(true, Ordering::Release);
        let rss = observer
            .join()
            .map_err(|_| "comparison RSS sampler failed")?;
        Ok((result?, rss))
    })
}

// This independent source-coordinate witness is opt-in for the exact fixture
// generated by tools/phase2a2_square.py. JPEG quality 70 permits a two-level
// grayscale tolerance; full-image equality alone cannot identify a wrong crop.
fn square_witness(
    pixels: &Pixels,
    crcs: &[(u32, u32)],
) -> Result<Vec<serde_json::Value>, AssetError> {
    let distinct: std::collections::BTreeSet<_> = crcs.iter().map(|(_, crc)| crc).collect();
    if distinct.len() != crcs.len() {
        return Err("square fixture useful regions must have distinct CRC32 witnesses".into());
    }
    crcs.iter().map(|(edge, _)| {
        let tile = Tile::from_tag(*edge).ok_or("square coordinate witness requires a tile")?;
        let x = tile.x * TILE_EDGE + 16;
        let y = tile.y * TILE_EDGE + 16;
        let expected = (((x / 256 * 7 + x / 32 * 3) + (y / 256 * 11 + y / 32 * 5)) % 256) as u8;
        let rgba = pixels.get(edge).and_then(|image| image.get_pixel_checked(17, 17))
            .ok_or("square coordinate witness pixel missing")?.0;
        if rgba[3] != 255 || rgba[..3].iter().any(|gray| gray.abs_diff(expected) > 2) {
            return Err(format!("square pattern mismatch at source({x},{y}): expected gray {expected}, got {rgba:?}").into());
        }
        Ok(serde_json::json!({
            "tile": [tile.x, tile.y], "source_pixel": [x, y],
            "output_pixel": [17, 17], "expected_gray": expected, "rgba": rgba,
            "gray_tolerance": 2,
        }))
    }).collect()
}

/// Run serially with TACK_JPEG_REGION_FIXTURE pointing at the streamed fixture.
/// The 15-tile comparison adds one neighboring column, not a full prefetch ring.
/// Set TACK_JPEG_SQUARE_PATTERN=1 to independently verify source coordinates.
#[test]
#[ignore = "requires explicit 50k-square fixture and serial measurement slot"]
fn regional_provider_comparison() -> Result<(), AssetError> {
    let path = std::path::PathBuf::from(
        std::env::var_os("TACK_JPEG_REGION_FIXTURE")
            .ok_or("set TACK_JPEG_REGION_FIXTURE to the 50000-square JPEG")?,
    );
    let source_bytes = path.metadata()?.len();
    let pattern = std::env::var("TACK_JPEG_SQUARE_PATTERN").is_ok_and(|value| value == "1");
    let useful = rectangle(4)?;
    let full_ring = (189..194)
        .flat_map(|y| (189..195).map(move |x| Tile { mip: 0, x, y }.tag()))
        .collect::<Result<Vec<_>, _>>()?;
    if admissible_tiles([50_000; 2], &full_ring) {
        return Err("complete 6x5 prefetch ring must exceed bounded tile admission".into());
    }
    let single = useful.iter().map(|&edge| vec![edge]).collect();
    let bands = useful.chunks(4).map(<[u32]>::to_vec).collect();
    let cases = [
        ("single12", single, true),
        ("rectangle12", vec![useful.clone()], false),
        ("bands3x4", bands, false),
        ("adjacent15_neighbor_column", vec![rectangle(5)?], false),
    ];
    let mut canonical: Option<Pixels> = None;
    for (name, jobs, single) in cases {
        let start = Instant::now();
        let (mut measured, child_rss) = sampled(|| measure(&path, &jobs, single))?;
        let elapsed = start.elapsed().as_secs_f64();
        if let Some(canonical) = &canonical {
            for edge in &useful {
                if canonical.get(edge) != measured.pixels.get(edge) {
                    return Err(format!(
                        "regional comparison pixels differ for {name}, tile {edge}"
                    )
                    .into());
                }
            }
        }
        let useful_crcs: Vec<_> = useful
            .iter()
            .map(|&edge| (edge, crc32fast::hash(measured.pixels[&edge].as_raw())))
            .collect();
        let source_witnesses = if pattern {
            square_witness(&measured.pixels, &useful_crcs)?
        } else {
            Vec::new()
        };
        println!(
            "{}",
            serde_json::json!({
                "case": name, "source_size": [50_000, 50_000], "source_bytes": source_bytes,
                "origin_tile": [190, 190], "mip": 0, "useful_tiles": 12,
                "rust_profile": if cfg!(debug_assertions) { "test_debug" } else { "test_release" }, "full_prefetch_ring_tiles": 30,
                "full_prefetch_ring_admitted": false,
                "output_tiles": measured.pixels.len(), "helper_invocations": jobs.len(),
                "source_logical_reads": measured.source_reads,
                "read_amplification": measured.source_reads as f64 / source_bytes as f64,
                "native_crop_rgba_footprint_peak": measured.crop_peak,
                "aggregate_output_peak": measured.output_peak,
                "elapsed_seconds": elapsed, "sampled_child_rss_hwm_peak": child_rss,
                "child_rss_sampling_ms": 5, "useful_pixels_match": true,
                "comparison_reference_rgba_bytes": useful.iter().map(|edge| measured.pixels[edge].as_raw().len()).sum::<usize>(),
                "useful_tile_crc32": useful_crcs, "source_pattern_checked": pattern,
                "source_coordinate_witnesses": source_witnesses
            })
        );
        if canonical.is_none() {
            canonical = Some(std::mem::take(&mut measured.pixels));
        }
    }
    Ok(())
}
