[package]
name = "tack-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
tack-core.workspace = true
tack-assets.workspace = true
wgpu.workspace = true
bytemuck.workspace = true
tracing.workspace = true
image.workspace = true

[dev-dependencies]
pollster.workspace = true

[lints]
workspace = true
